"""
PDF Report Generator for IDP Agent
Builds a professional multi-section report using fpdf2.
"""
from fpdf import FPDF
from typing import List, Dict
from datetime import datetime


class ReportPDF(FPDF):
    DOC_TITLE = "IDP Intelligence Report"
    PRIMARY   = (34, 211, 238)   # cyan
    DARK      = (2, 6, 23)       # near-black
    MID       = (30, 41, 59)     # slate-800
    LIGHT     = (148, 163, 184)  # slate-400

    def header(self):
        self.set_fill_color(*self.DARK)
        self.rect(0, 0, 210, 18, 'F')
        self.set_font("Helvetica", "B", 11)
        self.set_text_color(*self.PRIMARY)
        self.set_y(5)
        self.cell(0, 8, self.DOC_TITLE, align="C")

    def footer(self):
        self.set_y(-12)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(*self.LIGHT)
        self.cell(0, 8, f"Generated by IDP Intelligence Agent  ·  Page {self.page_no()}", align="C")

    def section_title(self, title: str):
        self.ln(6)
        self.set_fill_color(*self.MID)
        self.set_text_color(*self.PRIMARY)
        self.set_font("Helvetica", "B", 11)
        self.cell(0, 9, f"  {title}", fill=True, ln=True)
        self.ln(3)

    def body_text(self, text: str, indent: int = 0):
        self.set_text_color(220, 230, 242)
        self.set_font("Helvetica", "", 9)
        self.set_x(self.get_x() + indent)
        self.multi_cell(0, 5, text)
        self.ln(1)

    def metadata_row(self, label: str, value: str):
        self.set_font("Helvetica", "B", 9)
        self.set_text_color(*self.PRIMARY)
        self.cell(40, 6, label + ":")
        self.set_font("Helvetica", "", 9)
        self.set_text_color(220, 230, 242)
        # Using a standard cell instead of multi_cell to prevent the "Not enough horizontal space" crash
        self.cell(0, 6, str(value), align="L", ln=True)


def generate_pdf_report(
    filename: str,
    annotations: List[Dict],
    chat_history: List[Dict],
) -> bytes:
    """
    Build a styled PDF report and return raw bytes.
    """
    pdf = ReportPDF()
    pdf.set_auto_page_break(auto=True, margin=15)
    pdf.add_page()

    # ── Cover Section ───────────────────────────────────────────────────────
    pdf.set_fill_color(*ReportPDF.DARK)
    pdf.rect(0, 0, 210, 297, 'F')  # Full-page dark bg

    pdf.ln(22)
    pdf.set_font("Helvetica", "B", 22)
    pdf.set_text_color(*ReportPDF.PRIMARY)
    pdf.cell(0, 10, "Document Intelligence Report", align="C", ln=True)

    pdf.ln(4)
    pdf.set_font("Helvetica", "", 11)
    pdf.set_text_color(*ReportPDF.LIGHT)
    pdf.cell(0, 8, "Powered by IDP Intelligence Agent + NVIDIA NIM", align="C", ln=True)

    # Divider
    pdf.ln(6)
    pdf.set_draw_color(*ReportPDF.PRIMARY)
    pdf.set_line_width(0.5)
    pdf.line(20, pdf.get_y(), 190, pdf.get_y())
    pdf.ln(6)

    # Document metadata
    pdf.section_title("Session Overview")
    pdf.metadata_row("Document", filename or "N/A")
    pdf.metadata_row("Generated", datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC"))
    pdf.metadata_row("Annotations", str(len(annotations)))
    pdf.metadata_row("Q&A Exchanges", str(len(chat_history)))

    # ── Annotations Section ─────────────────────────────────────────────────
    if annotations:
        pdf.section_title(f"Your Annotations  ({len(annotations)})")
        for i, ann in enumerate(annotations, 1):
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(*ReportPDF.PRIMARY)
            pdf.cell(0, 6, f"[{i}]  {ann.get('timestamp', '')}", ln=True)
            pdf.body_text(ann["text"], indent=4)
            pdf.ln(1)
    else:
        pdf.section_title("Your Annotations")
        pdf.body_text("No annotations were added for this session.")

    # ── Q&A History Section ─────────────────────────────────────────────────
    if chat_history:
        pdf.section_title(f"Q&A Chat History  ({len(chat_history)} exchanges)")
        for i, item in enumerate(chat_history, 1):
            # Question
            pdf.set_font("Helvetica", "B", 9)
            pdf.set_text_color(252, 211, 77)   # amber
            pdf.cell(0, 6, f"Q{i}  [{item.get('timestamp', '')}]  {item['query']}", ln=True)

            # Answer
            pdf.set_font("Helvetica", "", 9)
            pdf.set_text_color(220, 230, 242)
            pdf.multi_cell(0, 5, item["response"])
            pdf.ln(3)

            # Thin separator
            pdf.set_draw_color(50, 60, 80)
            pdf.set_line_width(0.2)
            pdf.line(15, pdf.get_y(), 195, pdf.get_y())
            pdf.ln(3)
    else:
        pdf.section_title("Q&A Chat History")
        pdf.body_text("No chat exchanges in this session.")

    return bytes(pdf.output())
